# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Renaud Cerrato
tagline:          ''
description:      '<font face="monospace" size="3"># cat /dev/brain > /dev/keyboard</font>'
url:              http://renaudcerrato.github.io

author:
  name:           'Renaud Cerrato'
  url:            https://www.github.com/renaudcerrato

paginate:         20

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Custom vars
version:          2.1.0

github:
  repo:           https://www.github.com/renaudcerrato

analytics:
  google:         'UA-84293519-1'

social:
  name: Renaud Cerrato
  links:
    - https://twitter.com/RenaudCerrato
    - https://www.linkedin.com/in/renaudcerrato
    - https://plus.google.com/+RenaudCerrato
    - https://github.com/renaudcerrato
