# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Renaud Cerrato
tagline:          ''
description:      '<font face="monospace" size="3"># cat /dev/brain > /dev/keyboard</font>'
url:              http://renaudcerrato.github.io

author:
  name:           'Renaud Cerrato'
  url:            https://www.github.com/renaudcerrato

paginate:         5

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://www.github.com/renaudcerrato

analytics:
  google:         'UA-84293519-1'
